name: Post release announcements

on:
  release:
    types:
      - published

jobs:
  slack-notification:
    name: Share recent changes with a channel
    runs-on: ubuntu-latest
    steps:
      - name: Send release notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_RELEASE_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "name": ${{ toJSON(github.event.release.name) }},
              "version": "${{ github.event.release.tag_name }}",
              "body": ${{ toJSON(github.event.release.body) }},
              "url": "${{ github.event.release.html_url }}"
            }
